name: Deploy to EC2

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Update to use version v3

    - name: Install SSH client
      run: sudo apt-get install -y openssh-client

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.7.2  # Update to use version v0.7.2

      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Copy deploy script to EC2
      run: scp -o StrictHostKeyChecking=no deploy.sh ubuntu@your-ec2-public-ip:/home/ubuntu/deploy.sh

    - name: Execute deploy script on EC2
      run: ssh -o StrictHostKeyChecking=no ubuntu@your-ec2-public-ip 'bash /home/ubuntu/deploy.sh'
